---

- file: dest={{jenkins_home}}/.ssh state=directory owner={{jenkins_user}} group={{jenkins_group}} mode=0700

- name: jenkins-ssh | Copy private keys
  copy: >
    src={{item}}
    dest={{jenkins_home}}/.ssh/{{item}}
    owner={{jenkins_user}}
    group={{jenkins_group}}
    mode=0600
  with_items: "{{jenkins_ssh_key_files}}"

- name: jenkins-ssh | Setup SSH hosts
  lineinfile: 
    line="{{item}}"
    insertafter="EOF"
    state="present"
    create="yes"
    mode="0644"
    dest="{{jenkins_home}}/.ssh/known_hosts"
    owner="{{jenkins_user}}"
  with_items: jenkins_ssh_fingerprints