---
# Install openjdk java 1.7

- name: Install openjdk Java 1.7
  apt: pkg={{item}} state=present update_cache=yes force=yes
  with_items:
    - openjdk-7-jdk

- name: Update alternatives
  alternatives: name=java path=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java

- name: Set JAVA_HOME system variable
  lineinfile: dest=/etc/environment regexp='^JAVA_HOME' line="JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64" state=present

- name: export JAVA_HOME
  template: src=openjdk dest=/etc/profile.d/openjdk.sh