---

- name: Installing required dependencies by apt-get
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - libxml2-dev
    - libxslt-dev
    - python-dev
    - python2.7
    - python2.7-dev
    - git
    - python-lxml

- name: Installing required dependencies by pip
  pip: name={{ item }}
  with_items:
    - boto
    - docker-py
