---

- name: tell the host about our servers it might want to ssh to
  known_hosts: path='/etc/ssh/ssh_known_hosts'
               host='git.epam.com'
               key="{{ lookup('file', 'git.epam.com.pub') }}"

