---

- name: Change port to custom
  become: yes
  become_user: "{{ ar_username }}"
  template: src=jetty.xml.j2 dest={{ ar_home }}/{{ install_name }}/conf/jetty.xml

- name: Fix startup script to work with service command
  become: yes
  become_user: "{{ ar_username }}"
  template: src=archiva.j2 dest={{ ar_home }}/{{ install_name }}/bin/archiva mode=u+rwx

- name: Create symbolic link
  file: src={{ ar_home }}/{{ install_name }}/bin/archiva dest=/etc/init.d/archiva state=link
 
- name: Register service and start
  service: name=archiva state=running enabled=yes
  notify: restart archiva
