---

- name: Create a new user for Apache Archiva
  user: name={{ ar_username }} shell=/bin/bash home={{ ar_home }} comment="Archiva User" uid=1040

- name: Download Apache Archiva bin
  become: yes
  become_user: "{{ ar_username }}"
  get_url: url={{ source_url }} dest={{ download_path }} mode=0440

- name: Unarchive Apache Archiva
  become: yes
  become_user: "{{ ar_username }}"
  unarchive: src={{ download_path }} dest={{ ar_home }} creates={{ ar_home }}/{{ install_name }} copy=no
