# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-6.7"

  config.vm.define "ansnode", primary: true do |ansnode|
    ansnode.vm.box = "bento/centos-6.7"
    ansnode.vm.network "private_network", ip: "192.168.56.10"
    ansnode.vm.provider "virtualbox" do |vb|
      vb.name = "ansnode"
    end
    ansnode.vm.provision "shell", inline: "echo Provision"
    ansnode.vm.provision "shell", inline: "sudo yum install -y git epel-release mc vsftpd gcc python-devel openssl-devel PyYAML python-Jinja2 python-httplib2 python-six"
    ansnode.vm.provision "shell", inline: "sudo /etc/init.d/vsftpd restart"
    ansnode.vm.provision "shell", inline: "sudo pip install ansible"
  end

  config.vm.define "zoo", autostart: false do |zoo|
    zoo.vm.network "private_network", ip: "192.168.56.20"
    zoo.vm.box = "puphpet/centos65-x64"
    zoo.vm.provider "virtualbox" do |vb|
      vb.name = "zoo"
    end
  end

  config.vm.define "ci", autostart: false do |ci|
    ci.vm.box = "debian/jessie64"
    ci.vm.network "private_network", ip: "192.168.56.21"
    ci.vm.provider "virtualbox" do |vb|
      vb.name = "ci-server"
    end
    ci.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    ci.vm.provision "shell", inline: "sudo groupadd jenkins"
    ci.vm.provision "shell", inline: "sudo useradd -G admin -d /home/jenkins -s /bin/bash jenkins"
    #ci.vm.provision "shell", inline: "sudo passwd jenkins"
  end

  config.vm.define "mob", autostart: false do |mob|
    mob.vm.box = "debian/jessie64"
    mob.vm.network "private_network", ip: "192.168.56.25"
    mob.vm.provider "virtualbox" do |vb|
      vb.name = "mob-server"
      vb.memory = "2048"
    end
    mob.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  end  

  config.vm.define "aemauthor", autostart: false do |aemauthor|
    aemauthor.vm.network "private_network", ip: "192.168.56.22"
    aemauthor.vm.box = "bento/centos-6.7"
    aemauthor.vm.provider "virtualbox" do |vb|
      vb.name = "aem-author"
    end
  end

  config.vm.define "aempublisher", autostart: false do |aempublisher|
    aempublisher.vm.network "private_network", ip: "192.168.56.23"
    aempublisher.vm.box = "bento/centos-6.7"
    aempublisher.vm.provider "virtualbox" do |vb|
      vb.name = "aem-publisher"
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/devkey.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      #echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end
   
end
