# -*- mode: ruby -*-
# vi: set ft=ruby :

# ** Local envs provisioning **
#
# Server #1 - Ansible node (CentOS 6.7)
# Server #2 - MOB server with predefined 'minecraft' user (Debian 8)
#

# pre-reqs:
#
# ~/.ssh/{id_rsa_mobdeploy.pem, id_rsa_mobdeploy.pub} - deployment key, added to mob-server repo
# ~/.ssh/{id_rsa_mobadmin.pem, id_rsa_mobadmin.pub} - MOB-Admin user key
#

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-6.7"

  config.vm.define "ansible", primary: true do |ansible|
    ansible.vm.box = "bento/centos-6.7"
    ansible.vm.network "private_network", ip: "192.168.56.10"
    ansible.vm.provider "virtualbox" do |vb|
      vb.name = "ansible"
    end
    ansible.vm.provision "shell", inline: "echo Provision"
    ansible.vm.provision "shell", inline: "sudo yum install -y git epel-release mc vsftpd gcc python-devel openssl-devel PyYAML python-Jinja2 python-httplib2 python-six"
    ansible.vm.provision "shell", inline: "sudo /etc/init.d/vsftpd restart"
    ansible.vm.provision "shell", inline: "sudo pip install ansible"
  end

  config.vm.define "mob", autostart: false do |mob|
    mob.vm.box = "debian/jessie64"
    mob.vm.network "private_network", ip: "192.168.56.25"
    mob.vm.provider "virtualbox" do |vb|
      vb.name = "mob-server"
      vb.memory = "2048"
    end
    mob.vm.synced_folder ".", "/vagrant", type: "virtualbox"

    mob.vm.provision "shell" do |s|
      s.inline = <<-SHELL
        sudo groupadd minecraft
        sudo useradd -g minecraft -m -d /home/minecraft -c "Minecraft user" -s /bin/bash minecraft
        sudo mkdir /home/minecraft/.ssh && sudo chown minecraft:minecraft /home/minecraft/.ssh && sudo chmod 700 /home/minecraft/.ssh
        sudo cat /vagrant/id_rsa_mobdeploy.pem >> /home/minecraft/.ssh/id_rsa_mobdeploy.pem
        sudo chown minecraft:minecraft /home/minecraft/.ssh/id_rsa_mobdeploy.pem && sudo chmod 400 /home/minecraft/.ssh/id_rsa_mobdeploy.pem
      SHELL
    end  

  end  

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa_mobadmin.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      #echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
  end
   
end
