---
# Install openjdk java 1.8

- name: Add apt repository for openjdk1.8 (Debian)
  apt_repository: repo="{{ item }}" state=present
  with_items:
    - 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'
    - 'deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main'

- name: Set licence selected
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886

- name: Auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  
- name: Install openjdk Java 1.8
  apt: pkg={{item}} state=present update_cache=yes force=yes
  with_items:
    - oracle-java8-installer

- name: Update alternatives
  alternatives: name=java path=/usr/lib/jvm/java-8-oracle/bin/java

- name: JAVA_HOME 1.8 profile delete
  file: path=/etc/profile.d/{{item}} state=absent
  with_items:
    - jdk.sh
    - jdk.csh

- name: Set JAVA_HOME system variable
  lineinfile: dest=/etc/environment regexp='^JAVA_HOME' line="JAVA_HOME=/usr/lib/jvm/java-8-oracle" state=present

- name: export JAVA_HOME
  template: src=openjdk dest=/etc/profile.d/openjdk.sh