---

jenkins_name: jenkins
jenkins_user: jenkins
jenkins_group: jenkins
jenkins_configuration: /etc/default/jenkins
jenkins_home: /media/workspaces/jenkins  # Jenkins home location
jenkins_root: /usr/share/jenkins         # Location of jenkins arch indep files
jenkins_http_host: 127.0.0.1             # Set HTTP host
jenkins_http_port: 8080                  # Set HTTP port
jenkins_url: http://{{ jenkins_http_host }}:{{ jenkins_http_port }}
jenkins_maxopenfiles: 8192

jenkins_apt_key: http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key
jenkins_apt_key_id: D50582E6
jenkins_apt_repository: deb http://pkg.jenkins-ci.org/debian-stable binary/

# Set known hosts for ssh
jenkins_ssh_fingerprints:
  - "github.com,204.232.175.90 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="

# Private keys for Jenkins deployments
jenkins_ssh_key_files: [id_rsa_authmereloaded.pem,id_rsa_bungecoord.pem,id_rsa_mobdeploy.pem,id_rsa_mobadmin.pem]

# Ensure the packages installed
jenkins_apt_packages: [git,subversion,maven,ruby,ruby-sass]

# Ensure the plugins is installed
jenkins_plugins: [artifactory,artifactdeployer,artifact-promotion,backup,config-file-provider,copyartifact,deploy,dynamicparameter,git,git-parameter,git-server,m2release,mailer,maven-plugin,parameterized-trigger,scp,scriptler,ssh,ssh-slaves,token-macro,translation,timestamper,uno-choice]

jenkins_java: /usr/bin/java
jenkins_java_args:
  - "-Djava.awt.headless=true"
jenkins_pidfile: /var/run/jenkins/jenkins.pid
jenkins_prefix: "/"
jenkins_run_standalone: yes
jenkins_war: "{{ jenkins_root }}/jenkins.war"

# System config
# =============
jenkins_system_config:
  admin_email: nobody@example.com

# Logging
# =======
jenkins_log: "{{ jenkins_logdir }}/{{ jenkins_name }}.log"
jenkins_logdir: /var/log/jenkins            # Jenkins logs location
jenkins_logrotate: yes                      # Rotate Jenkins logs.
jenkins_logrotate_options:
  - compress
  - copytruncate
  - daily
  - dateext
  - rotate 7
  - size 10M