---

- name: Create a database for the server
  mysql_db: name={{ db_name }} state=present
  
- name: Create the database users
  mysql_user: name={{ item.name }}  password={{ item.pass|default("111") }}  
              priv={{ item.priv|default("*.*:ALL") }} state=present host={{ item.host | default("localhost") }}
  with_items: "{{ db_users }}"
  when: db_users|lower() != 'none'

- name: Copy a database dump file to remote host
  copy: src={{ db_dump }} dest=/tmp

- name: Restore it to the server database
  mysql_db: name={{ db_name }} state=import target=/tmp/{{ db_dump }}
