---

- name: Check if a user has added to sudores and validate it before saving
  lineinfile: dest=/etc/sudoers state=present regexp='^{{ minecraft_user }} ALL\=' line='{{ minecraft_user }} ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Pre-configure git 
  template: src=config.j2 dest={{ minecraft_home }}/.ssh/config owner=minecraft group=minecraft mode=0644

- name: Pre-configure git 
  template: src=gitconfig.j2 dest={{ minecraft_home }}/.gitconfig owner=minecraft group=minecraft mode=0644

- name: Create a project folder if not exists
  file: path={{ server_folder }} state=directory mode=0755 owner=minecraft group=minecraft

- name: Tell the host about our servers it might want to ssh to
  known_hosts: path='/etc/ssh/ssh_known_hosts'
               host='github.com'
               key="{{ lookup('file', 'github.com.pub') }}"
 
- name: Checkout servers repo
  become: yes
  become_user: "{{ minecraft_user }}"
  become_method: sudo
  git: repo=git@github.com:DmitryRendov/mob-server.git dest={{ server_folder }} force=yes

- name: Setup server configuration
  template: src={{ item.tmpl }} dest={{ item.dst }} owner=minecraft group=minecraft mode=0644
  with_items:
    - { tmpl: "./lobby/server.properties.j2", dst: "{{ server_folder }}/lobby/server.properties" }
    - { tmpl: "./lobby/spigot.yml.j2", dst: "{{ server_folder }}/lobby/spigot.yml" }
