---

- copy: src={{ item }} dest=/etc/init.d remote_src=true owner=root group=root mode="a+x"
  with_items:
    - "{{ server_folder }}/rc-scripts/bungeecord"
    - "{{ server_folder }}/rc-scripts/lobby"

#- service: name={{ item }} pattern={{ item }} state=stopped
#  with_items:
#    - bungeecord
#    - lobby
