# setup common system applications and configure Ansible node
#

- hosts: "{{env}}"
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - common
    - { role: java1.7-centos, when: ansible_os_family == "CentOS" }
    - { role: java1.7-debian, when: ansible_os_family == "Debian" }
