# setup common system applications and configure Ansible node
# ansible-playbook -i ./inventory/dev common.yml --extra-vars "env=mob env_type=prod" -vv

- hosts: "{{env}}"
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - common
