# Set java 7/8 to servers
#
# ansible-playbook -i ./inventory/dev java.yml --extra-vars "env=mob java_version=1.8" -vv

- hosts: "{{env}}"
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true
  max_fail_percentage: 0

  roles:
    - { role: java1.8-oracle-debian, when: ansible_os_family == "Debian" and java_version == "1.8"}
    - { role: java1.7-centos, when: ansible_os_family == "CentOS" and java_version == "1.7" }
    - { role: java1.7-debian, when: ansible_os_family == "Debian" and java_version == "1.7" }
