# Setup MOB server, including worlds
# source = yes - download worlds
# ansible-playbook -i ./inventory/dev mob-provision.yml --extra-vars "env=mob source=yes" -vv

- hosts: "{{env}}"
  user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true
  roles:
    - mob-provision

  vars_files:
    - host_vars/{{env}}